#!/bin/sh
# This file was automatically generated on Fri 09 Dec 2016 13:01:53 GMT from
# source: /dls_sw/work/R3.14.12.3/support/mapping/MappingBuilder/etc/makeIocs/mi_ex.xml
# 
# *** Please do not edit this file: edit the source file instead. ***
# 
cd "$(dirname "$0")"
if [ -n "$1" ]; then
    export EPICS_CA_SERVER_PORT="$(($1))"
    export EPICS_CA_REPEATER_PORT="$(($1 + 1))"
    [ $EPICS_CA_SERVER_PORT -gt 0 ] || {
        echo "First argument '$1' should be a integer greater than 0"
        exit 1
    }
fi
exec ./mi_ex stmi_ex.boot
