/* This file was automatically generated on Fri 09 Dec 2016 13:01:53 GMT from
 * source: /dls_sw/work/R3.14.12.3/support/mapping/MappingBuilder/etc/makeIocs/mi_ex.xml
 * 
 * *** Please do not edit this file: edit the source file instead. ***
 *  */
#include "epicsExit.h"
#include "epicsThread.h"
#include "iocsh.h"

int main(int argc, char *argv[])
{
    if(argc>=2) {
        iocsh(argv[1]);
        epicsThreadSleep(.2);
    }
    iocsh(NULL);
    epicsExit(0);
    return 0;
}

